LaundryERP/LaundryERP/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('usuarios/', include(('usuarios.urls', 'usuarios'), namespace='usuarios')),
    path('ordenes/', include(('ordenes.urls', 'ordenes'), namespace='ordenes')),
    path('ventas/', include(('ventas.urls', 'ventas'), namespace='ventas')),
    path('reportes/', include(('reportes.urls', 'reportes'), namespace='reportes')),
]

LaundryERP/ventas/urls.py
from django.urls import path
from . import views

app_name='ventas'

urlpatterns = [
    path('', views.lista_venta, name='lista_ventas'),
    path('detalle/<int:id>', views.detalle_venta, name='detalle_venta'),
    path('crear/', views.crear_venta, name='crear_venta'),
    path('eliminar/<int:id>', views.eliminar_venta, name='eliminar_venta'),
    path('actualizar_venta/<int:id>', views.actualizar_venta, name='actualizar_venta'),
]

LaundryERP/LaundryERP/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    return render(request, 'index.html')

LaundryERP/LaundryERP/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>{% block title %}LaundryERP{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'index' %}">LaundryERP</a>
        <ul class="navbar-nav">
            <li class="navbar-iten"> <a class="nav-link"  href="{% url 'ordenes:index' %}">Ordenes</a></li>
            <li class="navbar-iten"> <a class="nav-link" href="{% url 'ventas:index' %}">Ventas</a></li>
            <li class="navbar-iten"> <a class="nav-link" href="{% url 'Reportes:index' %}">Reportes</a></li>
            {% if request.user.is_authenticated and request.user.rol=='admin'%}
                <li class="navbar-iten"> <a class="nav-link" href="{% url 'Empleados:index' %}">Empleados</a></li>
            {% endif %}    
        </ul>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
        
</body>
</html>

LaundryERP/LaundryERP/templates/index.html
{% extends 'base.html' %}
{% block title %}Pagina Principal{% endblock %}
{%block content%}
<div class="container mt-4">
    <h1>Hola Bienvenido, {{ request.user.first_name }} a la Lavanderia</h1>
    <p>La session a iniciado con exito.</p>

</div>
{% endblock %}