LaundryERP/LaundryERP/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('usuarios/', include(('usuarios.urls', 'usuarios'), namespace='usuarios')),
    path('ordenes/', include(('ordenes.urls', 'ordenes'), namespace='ordenes')),
    path('ventas/', include(('ventas.urls', 'ventas'), namespace='ventas')),
    path('reportes/', include(('reportes.urls', 'reportes'), namespace='reportes')),
]

LaundryERP/ventas/urls.py
from django.urls import path
from . import views

app_name='ventas'

urlpatterns = [
    path('', views.lista_venta, name='lista_ventas'),
    path('detalle/<int:id>', views.detalle_venta, name='detalle_venta'),
    path('crear/', views.crear_venta, name='crear_venta'),
    path('eliminar/<int:id>', views.eliminar_venta, name='eliminar_venta'),
    path('actualizar_venta/<int:id>', views.actualizar_venta, name='actualizar_venta'),
]

LaundryERP/ventas/models.py
from django.db import models
from ordenes.models import OrdenDeServicio

# Create your models here.

class Venta(models.Model):
    METODOS_DE_PAGO=[
        ('efectivo', 'Efectivo'),
        ('tarjeta', 'Tarjeta de Debito o Credito'),
        ('cheque', 'Cheque'),
    ]

    orden_servicio=models.OneToOneField(OrdenDeServicio, on_delete=models.CASCADE)
    monto_total=(models.DecimalField(max_digits=10, decimal_places=2))
    fecha_venta=models.DateTimeField(auto_now_add=True) #Hay que agregar el auto now_add
    metodo_pago=models.CharField(max_length=20, choices=METODOS_DE_PAGO)
    

    def __str__(self):
        return f"Venta #{self.id} - ${self.monto_total}"

LaundryERP/ventas/forms.py
from django import forms
from .models import OrdenDeServicio
from usuarios.models import Usuario
from ventas.models import Venta
from django.contrib.auth.forms import AuthenticationForm

class VentaForm(forms.ModelForm):
    class Meta: 
        model = Venta
        fields = ['orden_servicio', 'monto_total', 'metodo_pago']
        widgets = {
            'orden_servicio': forms.Select(attrs={'class': 'form-control'}),
            'monto_total': forms.NumberInput(attrs={'class': 'form-control', 'placeholder':'Monto Total'}),
            'metodo_pago': forms.Select(attrs={'class': 'form-control'}),
        }
        
        def __init__(self, *args, **kwargs):
            super(VentaForm,self).__init__(*args, **kwargs)
            self.fields['orden_servicio'].queryset = OrdenDeServicio.objects.filter(pago_realizo=False)
            







'''METODOS_DE_PAGO=[
        ('efectivo', 'Efectivo'),
        ('tarjeta', 'Tarjeta de Debito o Credito'),
        ('cheque', 'Cheque'),
    ]

    orden_servicio=models.OneToOneField(OrdenDeServicio, on_delete=models.CASCADE)
    monto_total=(models.DecimalField(max_digits=10, decimal_places=2))
    fecha_venta=models.DateTimeField(auto_now_add=True) #Hay que agregar el auto now_add
    metodo_pago=models.CharField(max_length=20, choices=METODOS_DE_PAGO)'''

LaundryERP/ventas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import VentaForm
from.models import Venta
from django.contrib import messages

# Create your views here.

def lista_venta(request):
    ventas = Venta.objects.all()
    return render(request,'ordenes/lista_venta.html',{'ventas':ventas})

def detalle_venta(request, id):
    venta = get_object_or_404(Venta, id=id)
    return render(request,'venta/detalle_venta.html',{'venta':venta})

def crear_venta(request):
    if request.method == 'POST':
        form = Venta(request.POST)
        if form.is_valid():
            venta = form.save()
            venta.orden_servicio.pago_realizado=True
            venta.orden_servicio.save()    
            messages.success(request, 'La venta ha sido creada con éxito!')
            return redirect('ventas:lista_venta')
    else:
        form = VentaForm()      
    return render(request,'ventas/crear_venta.html', {'form':form})
 
def actualizar_venta(request, id):
    venta = get_object_or_404(Venta, id=id)
    if request.method == 'POST':
        form = Venta(request.POST, instance=venta)
        if form.is_valid():
            form.save()
            messages.success(request, f'La venta {venta.id}  ha sido actualizada')
            return redirect('ventas:lista_ventas.html')
    else:
        form = Venta(instance=venta)  # Pass the instance to the form for pre-filling the form fields with the current data.
    return render(request, 'venta/actualizar_venta.html', {'form': form, 'venta': venta})
        

def eliminar_venta(request, id):
    venta = get_object_or_404(Venta, id=id)
    if request.method == 'POST':
        venta.delete()
        messages.success(request, f'La venta {venta.id} ha sido eliminada')
        return redirect('ventas:lista_ventas')
    return render(request, 'ventas/eliminar_venta.html', {'venta': venta})

LaundryERP/ventas/templates/ventas/detalle_venta.html
{% extends 'base.html' %}
{% block title %}Detalle de la Venta{% endblock %}
{%block content%}
<h1>Detalle de la Venta {{orden.id}}</h1>

<p><strong>Orden Asociada:</strong> {{ venta.orden_servicio.id}}</p>

<p><strong>Monto Total:</strong> ${{ venta.monto_total }}</p>

<p><strong>Metodo de Pago:</strong> {{ venta.get_metodo_pago_display }}</p>

<p><strong>Fecha de Venta:</strong>{{ venta.fecha_venta }}</p>

<a href="{% url 'ventas:lista_ventas' %}" class="btn btn-secondary">Ir a Lista de Venta</a> 

{% endblock %}

LaundryERP/ventas/templates/ventas/lista_ventas.html
{% extends 'base.html' %}
{% block title %} Listado de Ventas {% endblock %}
{%block content%}
<div class="container mt-4"> 

    <h2>Lista de Ventas</h2>
    <a href="{% ventas:crear_venta %}" class="btn btn-primary">Crear Nueva Venta</a>
    <table class="table mt-4">
        <thead>
            <tr>
                <th>ID</th>
                <th>Orden</th>
                <th>Monto Total</th>
                <th>Metodo de Pago</th>
                <th>Fecha</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for venta in ventas %}
            <tr>
                <td>{{ venta.id }}</td>
                <td>{{ venta.orden_servicio.id }}</td>
                <td>{{ venta.monto_total }}</td>
                <td>{{ venta.get_metodo_pago_display }}</td>
                <td>{{ venta.fecha_venta }}</td>
                <td>
                    <a href="{% url 'ventas:detalle_venta' id=venta.id %}" class="btn btn-info">Detalles</a>
                    <a href="{% url 'ventas:actualizar_venta' id=venta.id %}" class="btn btn-warning">Editar</a>
                    <a href="{% url 'ventas:eliminar_venta' id=venta.id %}" class="btn btn-danger">Eliminar</a>
                </td>
            </tr>
            {% endfor %}


        </tbody>

    </table>
</div>
{% endblock %}