LaundryERP/LaundryERP/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('usuarios/', include(('usuarios.urls', 'usuarios'), namespace='usuarios')),
    path('ordenes/', include(('ordenes.urls', 'ordenes'), namespace='ordenes')),
    path('ventas/', include(('ventas.urls', 'ventas'), namespace='ventas')),
    path('reportes/', include(('reportes.urls', 'reportes'), namespace='reportes')),
]

LaundryERP/ordenes/urls.py
from django.urls import path
from . import views

app_name='ordenes'

urlpatterns = [
    path('', views.lista_ordenes, name='lista_ordenes'),
    path('detalle/<int:id>', views.detalle_orden, name='detalle_orden'),
    path('crear/', views.crear_orden, name='crear_orden'),
    path('eliminar/<int:id>', views.eliminar_orden, name='eliminar_orden'),
    path('actualizar_estado/<int:id>', views.actualizar_estado, name='actualizar_estado'),
    path('crear_cliente/', views.crear_cliente, name='crear_cliente'),
    path('lista_clientes/', views.lista_clientes, name='lista_clientes'),
    path('crear_prenda/', views.crear_prenda, name='crear_prenda'),
    path('lista_prendas/', views.lista_prendas, name='lista_prendas'),
    path('editar_prenda/<int:id>', views.editar_prenda, name='editar_prenda'),
    path('eliminar_prenda/<int:id>', views.eliminar_prenda, name='eliminar_prenda')   
]

LaundryERP/ventas/urls.py
from django.urls import path
from . import views

app_name='ventas'

urlpatterns = [
    path('', views.lista_venta, name='lista_ventas'),
    path('detalle/<int:id>', views.detalle_venta, name='detalle_venta'),
    path('crear/', views.crear_venta, name='crear_venta'),
    path('eliminar/<int:id>', views.eliminar_venta, name='eliminar_venta'),
    path('actualizar_venta/<int:id>', views.actualizar_venta, name='actualizar_venta'),
]

LaundryERP/ordenes/models.py
from django.db import models
from usuarios.models import Usuario

# Create your models here.
class Prenda(models.Model):
    TIPO_PRENDA_CHOICES =  [
        ('pantalon', 'Pantalón'),
        ('camisa', 'Camisa'),
        ('saco', 'Saco'),
        ('calcetines', 'Calcetines'),
        ('zapatos', 'Zapatos'),
        ('medias', 'Medias'),
        ('blusa', 'Blusa'),
        ('chaleco', 'Chaleco'),
        ('traje', 'Traje'),
        ('pantalones_jeans', 'Pantalones Jeans'),
        ('chaquetas', 'Chaquetas'),
        ('jeans', 'Jeans'),
        ('jersey', 'Jersey'),
        ('sweater', 'Sweater'),
        ('t-shirt', 'T-Shirt'),
        ('buzo', 'Buzo'),
        ('sudadera', 'Sudadera'),
        ('pantalones_shorts', 'Pantalones Shorts'),
    ]
    tipo_prenda=models.CharField(max_length=50, choices=TIPO_PRENDA_CHOICES, default= 'pantalon') 
    precio=models.DecimalField(max_digits=10, decimal_places=2)
    descripcion=models.TextField()

    def __str__(self):
        return f'{self.tipo_prenda} - {self.precio}'
# crear el modelo cliente 
class Cliente(models.Model):
    nombre=models.CharField(max_length=100)
    apellido=models.CharField(max_length=100)
    telefono=models.CharField(max_length=15)
    correo=models.EmailField(unique=True) #con unique=true se establece para que los correos sean unicos
    direccion=models.TextField()
    
    def __str__(self):
        return self.nombre

     
#Creacion de modelo de Orden de servicio 
class OrdenDeServicio(models.Model):
    ESTADOS=[
        ('pendiente', 'Pendiente'),
        ('proceso', 'En Proceso'),
        ('completada', 'Completada')
    ]

    cliente=models.ForeignKey(Cliente, on_delete=models.CASCADE)
    empleado=models.ForeignKey(Usuario, on_delete=models.SET_NULL,null=True)
    prendas=models.ManyToManyField(Prenda, related_name='ordenes'), #Se asocia mas de una prenda a la orden y la misma prenda puede estar en varias ordenes
    fecha_creacion=models.DateTimeField(auto_now_add=True) # no se requiere agregar mas parametros 
    estado=models.CharField(max_length=20 , choices=ESTADOS, default='pendiente') #'pendiente', va el valor no la etiqueta
    total=models.DecimalField(max_digits=10, decimal_places=2, default=0)
    pago_realizado=models.BooleanField(default=False)

    #Calculo del total de la orden sumando los precios de las prendas asociadas
    def calculo_total(self):
        self.total=sum(prenda.precio for prenda in self.prendas.all())
        self.save()
        return self.total


    def __str__(self):   # devielve cadena de caracteres 
        return f"Orden #{self.id} - {self.cliente.nombre} - {self.estado} - {self.total}"

LaundryERP/ordenes/forms.py
from django import forms
from .models import OrdenDeServicio, Prenda, Cliente 
from usuarios.models import Usuario  
from django.contrib.auth.forms import AuthenticationForm


class OrdenDeServicioForm(forms.ModelForm):
    class Meta:  
        model = OrdenDeServicio
        fields = ['cliente', 'empleado', 'prendas', 'estado']
        
    cliente = forms.ModelChoiceField(queryset=Cliente.objects.all(), empty_label='Seleccione un Cliente', widget=forms.Select(attrs={'class': 'form-control'}))
    empleado = forms.ModelChoiceField(queryset=Usuario.objects.filter(rol='empleado'), empty_label='Seleccione un Empleado', widget=forms.Select(attrs={'class': 'form-control'}))
    estado = forms.ChoiceField(choices=OrdenDeServicio.ESTADOS, initial='pendiente', widget=forms.Select(attrs={'class': 'form-control'}))
    prendas = forms.ModelMultipleChoiceField(queryset=Prenda.objects.all(), widget=forms.CheckboxSelectMultiple(attrs={'class': 'form-control'}))
    def __init__(self, *args, **kwargs):
        super(OrdenDeServicioForm,self).__init__(*args, **kwargs)
        self.fields['estado'].widget.attrs.update({'class': 'form-control'})
        self.fields['cliente'].widget.attrs.update({'class': 'form-control'})
        self.fields['empleado'].widget.attrs.update({'class': 'form-control'})
        self.fields['prendas'].widget.attrs.update({'class': 'form-control'})
        
class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nombre','apellido', 'correo', 'direccion', 'telefono']
        widgets = {
            'nombre': forms.TextInput(attrs = {'class': 'form-control'}),
            'apellido': forms.TextInput(attrs = {'class': 'form-control'}),
            'correo': forms.EmailInput(attrs = {'class': 'form-control'}),
            'direccion': forms.Textarea(attrs = {'class': 'form-control'}),
            'telefono': forms.TextInput(attrs = {'class': 'form-control'}),
        }

class PrendaForm(forms.ModelForm):
    class Meta:
        model = Prenda
        fields = ['tipo_prenda', 'precio', 'descripcion']
        widgets = {
            'tipo_prenda': forms.Select(attrs = {'class': 'form-control'}),
            'precio': forms.NumberInput(attrs = {'class': 'form-control'}),
            'descripcion': forms.Textarea(attrs = {'class': 'form-control'}),
        }

LaundryERP/ordenes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import OrdenDeServicio, Cliente, Prenda
from .forms import OrdenDeServicioForm, ClienteForm, PrendaForm 
from django.contrib import messages

# Create your views here.

def lista_ordenes(request):
    ordenes = OrdenDeServicio.objects.all()
    return render(request,'ordenes/lista_ordenes.html',{'ordenes':ordenes})

def detalle_orden(request, id):
    orden = get_object_or_404(OrdenDeServicio, id=id)
    return render(request,'ordenes/detalle_orden.html',{'orden':orden})

def crear_orden(request):
    if request.method == 'POST':
        form = OrdenDeServicioForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'La Orden ha sido creada con éxito!')
            return redirect('ordenes:lista_ordenes')
    else:
        form = OrdenDeServicioForm()      
    return render(request,'ordenes/crear_orden.html', {'form':form})
 
def actualizar_estado(request, id):
    orden = get_object_or_404(OrdenDeServicio, id=id)
    if request.method == 'POST':
        estado = request.post.get('estado')
        orden.estado = estado
        orden.save()
        messages.success(request, f'La Orden {orden.id}  ha sido actualizado a {estado}')
        return redirect('ordenes:detalle_orden.html', id=orden.id)
        
    return render(request, 'ordenes/actualizar_estado.html', {'orden': orden})

def eliminar_orden(request, id):
    orden = get_object_or_404(OrdenDeServicio, id=id)
    if request.method == 'POST':
        orden.delete()
        messages.success(request, f'La Orden {orden.id} ha sido eliminada')
        return redirect('ordenes:lista_ordenes')
    return render(request, 'ordenes/eliminar_orden.html', {'orden': orden})

def crear_cliente(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Cliente registrado exitosamente')
            return redirect('ordenes:lista_clientes')
    else:
        form = ClienteForm()
    return render(request, 'ordenes/crear_cliente.html', {'form': form})

def lista_clientes(request):
    clientes = Cliente.objects.all()
    return render(request, 'ordenes/lista_clientes.html', {'clientes': clientes})

#def eliminar_cliente(request):

def crear_prenda(request):
    if request.method == 'POST':
        form = PrendaForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Prenda registrada exitosamente')
            return redirect('ordenes:lista_prendas')
    else:
        form = PrendaForm()
    return render(request, 'ordenes/crear_prenda.html', {'form': form})

def lista_prendas(request):
    prendas = Prenda.objects.all()
    return render(request, 'ordenes/lista_prendas.html', {'prendas': prendas})

def editar_prenda(request, id):
    prenda = get_object_or_404(Prenda, id=id)
    if request.method == 'POST':
        form = PrendaForm(request.POST, instance= prenda)
        if form.is_valid():
            form.save()
            messages.success(request, 'La prenda ha sido actualizada de manera exitosa')
            return redirect('ordenes:lista_prendas')
    else:
        form = PrendaForm(instance= prenda)
    return render(request, 'ordenes/editar_prenda.html', {'form': form})
    
def eliminar_prenda(request, id):
    prenda = get_object_or_404(Prenda, id=id)
    if request.method == 'POST':
        prenda.delete()
        messages.success(request, f'La Prenda {prenda.id} ha sido eliminada')
        return redirect('ordenes:lista_prendas')
    return render(request, 'ordenes/eliminar_prenda.html', {'prenda': prenda})

LaundryERP/ordenes/templates/ordenes/actualizar_estado.html
{% extends 'base.html' %}
{% block title %}Actualizar Orden{% endblock %}
{%block content%}
<h1>Actualizar el Estado de la Orden</h1>

<p><strong>Cliente:</strong> {{ orden.cliente.nombre }}</p>

<p><strong>Empleado:</strong> {{ orden.Empleado.username }}</p>

<p><strong>Estado:</strong> {{ orden.estado }}</p>

<p><strong>Fecha de creación:</strong>{{ orden.fecha_creacion }}</p>

<p><strong>Total:</strong> ${{ orden.total }}</p>

<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="estado">Actualizar Estado:</label>
        <select class="form-control" id="estado" name="estado">
            <option value="pendiente" {% if orden.estado == 'pendiente' %} selected  {% endif %}>Pendiente</option>
            <option value="proceso" {% if orden.estado == 'proceso' %} selected  {% endif %}>En Proceso</option>
            <option value="finalizado" {% if orden.estado == 'completada' %} selected  {% endif %}>Completada</option>  
        </select>


    </div>
    <button type="submit" class="btn btn-primary">Actualizar</button>
</form>

{% endblock %}

LaundryERP/ordenes/templates/ordenes/crear_cliente.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css ' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Registrar Cliente</title>
</head>
<body>
    <div class="div1"></div>
    <div class="div2">
        <div class="div9">
            <nav class="navbar navbar-expand-lg rounded-top-navbar" style="background-color: rgb(4, 4, 46);">
            <div class="container-fluid">
              <a class="navbar-brand text-white" href="#">CUSTOMER</a>
              <!-- <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button> -->
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link text-white" href="#">Registration</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link text-white" href="#">Webpage</a>
                  </li>
                </ul>
                <div class="d-flex ms-3">
                    <button type="button" class="btn btn-outline-light" href="#">Registration</button>
                    <button type="button" class="btn btn-warning">Warning</button>
                </div>
              </div>
            </div>
          </nav></div>
        <div class="div10"></div>
        <div class="div11">
            <div class="container mt-5 ">
              <h2>Registrar Cliente</h2>
              <div class="row justify-content-center">
                  <div class="col-md-6">
                      <form class="card p-4 shadow" method="POST">
                          {% csrf_token %}
                          {{ form.as_p }}
                          <button type="submit" class="btn btn-primary">registrar</button>
                      </form>
                      {% if messages %}
                          <div class="mt-3">
                              {% for message in messages %}
                                  <div class="alert alert-{{message.tags}}">
                                      {{ message }}
                                  </div>
                              {% endfor %}
                          </div>
                      {% endif %}
                  </div>
              </div> 
        </div>
        </div>
        <div class="div12"></div>
        <div class="div13"></div>
    </div>
    <div class="div3"></div>
    <div class="div4"></div>
    <div class="div5"></div>
    <div class="div6"></div>
    <div class="div7"></div>
    <div class="div8"></div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

LaundryERP/ordenes/templates/ordenes/crear_orden.html
{% extends 'base.html' %}
{% block title %}Crear Orden{% endblock %}
{%block content%}
<h1>Crear Nueva Orden</h1>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Crear Orden</button>
</form>
{% endblock %}

LaundryERP/ordenes/templates/ordenes/crear_prenda.html
{% extends 'base.html' %}
{% block title %}Crear Prenda{% endblock %}
{%block content%}
<h1>Crear Nueva Prenda</h1>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>
{% endblock %}

LaundryERP/ordenes/templates/ordenes/detalle_orden.html
{% extends 'base.html' %}
{% block title %}Detalle de la Orden{% endblock %}
{%block content%}
<h1>Detalle de la Orden {{orden.id}}</h1>

<p><strong>Pedido realizado por:</strong> {{ orden.cliente.nombre }}</p>

<p><strong>Pedido tramitado por:</strong> {{ orden.Empleado.username }}</p>

<p><strong>Estado:</strong> {{ orden.estado }}</p>

<p><strong>Fecha de creación:</strong>{{ orden.fecha_creacion }}</p>

<p><strong>Total:</strong> ${{ orden.total }}</p>

<a href="{% url 'ordenes:actualizar_estado' orden.id %}" class="btn btn-warning">Actualizar Estado</a> 

<a href="{% url 'ordenes:eliminar_orden' orden.id %}" class="btn btn-danger" onclick="return confirm('¿Esta seguro que desea Eliminar esta orden?')">Eliminar Orden</a> 

{% endblock %}

LaundryERP/ordenes/templates/ordenes/editar_prenda.html
{% extends 'base.html' %}
{% block title %}Editar Prenda{% endblock %}
{%block content%}
<div class="container mt-5">
<h1>Editar Prenda</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit" class="btn btn-primary">Actualizar</button>
</form>
</div>

{% endblock %}

LaundryERP/ordenes/templates/ordenes/eliminar_orden.html
{% extends 'base.html' %}
{% block title %}Eliminar Orden{% endblock %}
{%block content%}
<h1>Confirmar Eliminacion de orden</h1>

<p>¿Estas seguro de eliminar la orden con el numero {{ order.id }}?</p>

<form method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Confirmar Eliminacion</button>
    <a href="{% url 'ordenes:lista_ordenes'%}" class="btn btn-secondary">Cancelar</a>
</form>

{% endblock %}

LaundryERP/ordenes/templates/ordenes/eliminar_prenda.html
{% extends 'base.html' %}
{% block title %}Eliminar Prenda{% endblock %}
{%block content%}
<h1>Confirmar Eliminacion de la prenda</h1>

<p>¿Estas seguro de eliminar la prenda con el numero {{ prenda.id }}?</p>

<form method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Confirmar Eliminacion</button>
    <a href="{% url 'ordenes:lista_ordenes'%}" class="btn btn-secondary">Cancelar</a>
</form>

{% endblock %}

LaundryERP/ordenes/templates/ordenes/lista_clientes.html
{% extends 'base.html' %}
{% block title %}Lista de Clientes{% endblock %}
{%block content%}
<div class="container mt-4"> 

    <h2>Lista de Clientes</h2>

        <table class="table">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Correo Electronico</th>
                    <th>Dirección</th>
                    <th>Telefono</th>
                </tr>
            </thead>
            <tbody>
                {% for cliente in clientes %}
                <tr>
                    <td>{{ cliente.nombre }}</td>
                    <td>{{ cliente.apellido }}</td>
                    <td>{{ cliente.correo }}</td>
                    <td>{{ cliente.direccion }}</td>
                    <td>{{ cliente.telefono }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="3">
                        <h5>No hay Clientes disponibles</h5>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

LaundryERP/ordenes/templates/ordenes/lista_ordenes.html
{% extends 'base.html' %}
{% block title %} Listado de Ordenes {% endblock %}
{%block content%}
<div class="container mt-4"> 

    <h2>Lista de Ordenes</h2>
    <a href="{% url 'ordenes:crear_orden' %}" class="btn btn-primary">Crear Nueva Orden</a>
    <table class="table mt-4">
        <thead>
            <tr>
                <th>ID</th>
                <th>Cliente</th>
                <th>Empleado</th>
                <th>Estado</th>
                <th>Fecha de Creacion</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for orden in ordenes %}
            <tr>
                <td>{{ orden.id }}</td>
                <td>{{ orden.cliente.nombre }}</td>
                <td>{{ orden.empleado.username }}</td>
                <td>{{ orden.estado }}</td>
                <td>{{ orden.fecha_creacion }}</td>
                <td>
                    <a href="{% url 'ordenes:detalle_orden' orden.id %}" class="btn btn-info">Detalles</a>
                    <a href="{% url 'ordenes:actualizar_estado' orden.id %}" class="btn btn-warning">Editar</a>
                    <a href="{% url 'ordenes:eliminar_orden' orden.id %}" class="btn btn-danger">Eliminar</a>
                </td>
            </tr>
            {% endfor %}


        </tbody>

    </table>
</div>
{% endblock %}

LaundryERP/ordenes/templates/ordenes/lista_prendas.html
{% extends 'base.html' %}
{% block title %} Listado de Prendas {% endblock %}
{%block content%}
<div class="container mt-4"> 

    <h2>Lista de Prendas</h2>
    <a href="{% url 'ordenes:crear_prenda' %}" class="btn btn-primary">registrar Nueva Prenda</a>

    <table class="table mt-4">
        <thead>
            <tr>
                <th>ID</th>
                <th>Tipo</th>
                <th>Descripción</th>
                <th>Precio</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for prenda in prendas %}
            <tr>
                <td>{{ prenda.id }}</td>
                <td>{{ prenda.get_tipo_prenda_display }}</td>
                <td>{{ prenda.descripcion }}</td>
                <td>{{ prenda.precio }}</td>
                <td>
                    <a href="{% url 'ordenes:editar_prenda' prenda.id %}" class="btn btn-warning">Editar</a>
                    <a href="{% url 'ordenes:eliminar_prenda' prenda.id %}" class="btn btn-danger">Eliminar</a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="4" class="text-center"> No hay prendas registradas</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}